# Settings for the [build] key are global and are applied to
# all deploy contexts unless overridden by a context-specific setting.
# Production context: all deploys from the Production branch
# set in your siteâ€™s Branches settings in the UI will inherit
# these settings. You can define environment variables
# here but we recommend using the Netlify UI for sensitive
# values to keep them out of your source repository.
[context.production]
  publish = "output/"
  command = "make publish"
  environment = { NODE_VERSION = "18.19.3" }